//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.Persistencia
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CalicoEntities : DbContext
    {
        public CalicoEntities()
            : base("name=CalicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIANCHI_PROCESS> BIANCHI_PROCESS { get; set; }
        public virtual DbSet<tblSubCliente> tblSubCliente { get; set; }
    
        public virtual int INTERFAZ_CrearProceso(Nullable<int> tipoProceso, Nullable<int> tipoMensaje)
        {
            var tipoProcesoParameter = tipoProceso.HasValue ?
                new ObjectParameter("tipoProceso", tipoProceso) :
                new ObjectParameter("tipoProceso", typeof(int));
    
            var tipoMensajeParameter = tipoMensaje.HasValue ?
                new ObjectParameter("tipoMensaje", tipoMensaje) :
                new ObjectParameter("tipoMensaje", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INTERFAZ_CrearProceso", tipoProcesoParameter, tipoMensajeParameter);
        }
    }
}
