//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistoricoPedido
    {
        public int hpec_hisp_id { get; set; }
        public string hpec_emplazamiento { get; set; }
        public string hpec_almacen { get; set; }
        public string hpec_tped_codigo { get; set; }
        public string hpec_letra { get; set; }
        public string hpec_sucursal { get; set; }
        public decimal hpec_numero { get; set; }
        public System.DateTime hpec_fechaEmision { get; set; }
        public System.DateTime hpec_fechaEntrega { get; set; }
        public string hpec_cliente { get; set; }
        public string hpec_destinatario { get; set; }
        public string hpec_razonSocial { get; set; }
        public string hpec_pais { get; set; }
        public string hpec_provincia { get; set; }
        public string hpec_codigoPostal { get; set; }
        public string hpec_localidad { get; set; }
        public string hpec_domicilio { get; set; }
        public string hpec_centroCosto { get; set; }
        public string hpec_areaMuelle { get; set; }
        public decimal hpec_numeroRuteo { get; set; }
        public bool hpec_entregaParcial { get; set; }
        public decimal hpec_importeFactura { get; set; }
        public decimal hpec_contraRembolso { get; set; }
        public decimal hpec_prioridad { get; set; }
        public string hpec_referenciaA { get; set; }
        public string hpec_referenciaB { get; set; }
        public string hpec_observaciones { get; set; }
    }
}
