//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistoricoRecepcion
    {
        public int hrec_hisp_id { get; set; }
        public string hrec_emplazamiento { get; set; }
        public string hrec_almacen { get; set; }
        public string hrec_trec_codigo { get; set; }
        public string hrec_numero { get; set; }
        public System.DateTime hrec_fechaEmision { get; set; }
        public System.DateTime hrec_fechaEntrega { get; set; }
        public string hrec_proveedor { get; set; }
        public string hrec_contacto { get; set; }
        public string hrec_despacho { get; set; }
        public string hrec_ordenCompra { get; set; }
        public string hrec_motivoDevolucion { get; set; }
        public string hrec_observaciones { get; set; }
    }
}
