//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInformePedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInformePedido()
        {
            this.tblInformePedidoDetalle = new HashSet<tblInformePedidoDetalle>();
        }
    
        public int ipec_proc_id { get; set; }
        public string ipec_emplazamiento { get; set; }
        public string ipec_almacen { get; set; }
        public string ipec_tipo { get; set; }
        public string ipec_letra { get; set; }
        public string ipec_sucursal { get; set; }
        public decimal ipec_numero { get; set; }
        public decimal ipec_global { get; set; }
        public decimal ipec_remito { get; set; }
        public System.DateTime ipec_fechaPicking { get; set; }
        public System.DateTime ipec_fechaFinProceso { get; set; }
        public string ipec_cliente { get; set; }
        public string ipec_destinatario { get; set; }
        public string ipec_provincia { get; set; }
        public string ipec_codigoPostal { get; set; }
        public string ipec_localidad { get; set; }
        public string ipec_domicilio { get; set; }
        public string ipec_centroCosto { get; set; }
        public string ipec_camion { get; set; }
        public string ipec_areaMuelle { get; set; }
        public decimal ipec_numeroRuteo { get; set; }
        public bool ipec_entregaParcial { get; set; }
        public decimal ipec_importeFactura { get; set; }
        public decimal ipec_contraRembolso { get; set; }
        public decimal ipec_prioridad { get; set; }
        public string ipec_referenciaA { get; set; }
        public string ipec_referenciaB { get; set; }
        public string ipec_observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInformePedidoDetalle> tblInformePedidoDetalle { get; set; }
    }
}
