//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInformeRecepcionDetalle
    {
        public int ired_id { get; set; }
        public int ired_proc_id { get; set; }
        public decimal ired_linea { get; set; }
        public string ired_compania { get; set; }
        public string ired_producto { get; set; }
        public string ired_lote { get; set; }
        public System.DateTime ired_vencimiento { get; set; }
        public string ired_serie { get; set; }
        public decimal ired_cantidadOriginal { get; set; }
        public decimal ired_cantidadRecibida { get; set; }
        public string ired_estado { get; set; }
        public decimal ired_precioUnitario { get; set; }
        public string ired_ordenCompra { get; set; }
        public string ired_tipoPedido { get; set; }
        public string ired_letraPedido { get; set; }
        public string ired_sucursalPedido { get; set; }
        public decimal ired_numeroPedido { get; set; }
        public decimal ired_lineaPedido { get; set; }
    
        public virtual tblInformeRecepcion tblInformeRecepcion { get; set; }
    }
}
