//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInformeRecepcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInformeRecepcion()
        {
            this.tblInformeRecepcionDetalle = new HashSet<tblInformeRecepcionDetalle>();
        }
    
        public int irec_proc_id { get; set; }
        public Nullable<System.DateTime> irec_fecha { get; set; }
        public string irec_emplazamiento { get; set; }
        public string irec_almacen { get; set; }
        public string irec_tipo { get; set; }
        public string irec_numero { get; set; }
        public Nullable<System.DateTime> irec_fechaEmision { get; set; }
        public Nullable<System.DateTime> irec_fechaEntrega { get; set; }
        public string irec_proveedor { get; set; }
        public string irec_contacto { get; set; }
        public string irec_despacho { get; set; }
        public string irec_observaciones { get; set; }
        public Nullable<bool> irec_devolucion { get; set; }
        public string irec_motivoDevolucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInformeRecepcionDetalle> tblInformeRecepcionDetalle { get; set; }
    }
}
