//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInformePedidoDetalle
    {
        public int iped_id { get; set; }
        public int iped_proc_id { get; set; }
        public decimal iped_controlInterno { get; set; }
        public decimal iped_linea { get; set; }
        public string iped_compania { get; set; }
        public string iped_producto { get; set; }
        public string iped_lote { get; set; }
        public System.DateTime iped_vencimiento { get; set; }
        public string iped_serie { get; set; }
        public decimal iped_cantidad { get; set; }
        public string iped_estado { get; set; }
    
        public virtual tblInformePedido tblInformePedido { get; set; }
    }
}
