//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProceso
    {
        public int proc_id { get; set; }
        public System.DateTime proc_fechaIngreso { get; set; }
        public System.DateTime proc_fechaEjecucion { get; set; }
        public int proc_tipoProceso { get; set; }
        public int proc_tipoMensaje { get; set; }
        public string proc_identificador { get; set; }
    
        public virtual tblInformePedido tblInformePedido { get; set; }
        public virtual tblInformeRecepcion tblInformeRecepcion { get; set; }
        public virtual tblPedido tblPedido { get; set; }
        public virtual tblRecepcion tblRecepcion { get; set; }
        public virtual tblSubCliente tblSubCliente { get; set; }
    }
}
