//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPedido()
        {
            this.tblPedidoDetalle = new HashSet<tblPedidoDetalle>();
        }
    
        public int pedc_proc_id { get; set; }
        public string pedc_emplazamiento { get; set; }
        public string pedc_almacen { get; set; }
        public string pedc_tped_codigo { get; set; }
        public string pedc_letra { get; set; }
        public string pedc_sucursal { get; set; }
        public decimal pedc_numero { get; set; }
        public System.DateTime pedc_fechaEmision { get; set; }
        public System.DateTime pedc_fechaEntrega { get; set; }
        public string pedc_cliente { get; set; }
        public string pedc_destinatario { get; set; }
        public string pedc_razonSocial { get; set; }
        public string pedc_pais { get; set; }
        public string pedc_provincia { get; set; }
        public string pedc_codigoPostal { get; set; }
        public string pedc_localidad { get; set; }
        public string pedc_domicilio { get; set; }
        public string pedc_centroCosto { get; set; }
        public string pedc_areaMuelle { get; set; }
        public decimal pedc_numeroRuteo { get; set; }
        public bool pedc_entregaParcial { get; set; }
        public decimal pedc_importeFactura { get; set; }
        public decimal pedc_contraRembolso { get; set; }
        public decimal pedc_prioridad { get; set; }
        public string pedc_referenciaA { get; set; }
        public string pedc_referenciaB { get; set; }
        public string pedc_observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedidoDetalle> tblPedidoDetalle { get; set; }
        public virtual tblProceso tblProceso { get; set; }
    }
}
