//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico.persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecepcionDetalle
    {
        public int recd_id { get; set; }
        public int recd_proc_id { get; set; }
        public decimal recd_linea { get; set; }
        public string recd_compania { get; set; }
        public string recd_producto { get; set; }
        public string recd_lote { get; set; }
        public System.DateTime recd_fechaVencimiento { get; set; }
        public string recd_serie { get; set; }
        public decimal recd_cantidad { get; set; }
        public decimal recd_precioUnitario { get; set; }
        public decimal recd_lineaPedido { get; set; }
        public string recd_numeroPedido { get; set; }
    
        public virtual tblRecepcion tblRecepcion { get; set; }
    }
}
