//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calico
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubCliente
    {
        public int subc_proc_id { get; set; }
        public string subc_codigo { get; set; }
        public string subc_codigoCliente { get; set; }
        public string subc_razonSocial { get; set; }
        public string subc_domicilio { get; set; }
        public string subc_localidad { get; set; }
        public string subc_codigoPostal { get; set; }
        public string subc_areaMuelle { get; set; }
        public string subc_telefono { get; set; }
        public decimal subc_diasVencimiento { get; set; }
        public bool subc_esProveedor { get; set; }
        public string subc_cuit { get; set; }
        public string subc_iva { get; set; }
        public string subc_correoElectronico { get; set; }
    }
}
